<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Playlist extends \Entity\Playlist implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPlaylist_id()
    {
        $this->__load();
        return parent::getPlaylist_id();
    }

    public function setPlaylist_id($Playlist_id)
    {
        $this->__load();
        return parent::setPlaylist_id($Playlist_id);
    }

    public function getPlaylist_name()
    {
        $this->__load();
        return parent::getPlaylist_name();
    }

    public function setPlaylist_name($Playlist_name)
    {
        $this->__load();
        return parent::setPlaylist_name($Playlist_name);
    }

    public function getPlaylist_created_date()
    {
        $this->__load();
        return parent::getPlaylist_created_date();
    }

    public function setPlaylist_created_date($Playlist_created_date)
    {
        $this->__load();
        return parent::setPlaylist_created_date($Playlist_created_date);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getPrivacy_type_id()
    {
        $this->__load();
        return parent::getPrivacy_type_id();
    }

    public function setPrivacy_type_id($privacy_type_id)
    {
        $this->__load();
        return parent::setPrivacy_type_id($privacy_type_id);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'Playlist_id', 'Playlist_name', 'Playlist_created_date', 'email', 'privacy_type_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}