<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Profile extends \Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getProfile_id()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["profile_id"];
        }
        $this->__load();
        return parent::getProfile_id();
    }

    public function setProfile_id($profile_id)
    {
        $this->__load();
        return parent::setProfile_id($profile_id);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getPrivacy_type_id()
    {
        $this->__load();
        return parent::getPrivacy_type_id();
    }

    public function setPrivacy_type_id($privacy_type_id)
    {
        $this->__load();
        return parent::setPrivacy_type_id($privacy_type_id);
    }

    public function getAbout_me()
    {
        $this->__load();
        return parent::getAbout_me();
    }

    public function setAbout_me($about_me)
    {
        $this->__load();
        return parent::setAbout_me($about_me);
    }

    public function getRelationship()
    {
        $this->__load();
        return parent::getRelationship();
    }

    public function setRelationship($relationship)
    {
        $this->__load();
        return parent::setRelationship($relationship);
    }

    public function getLooking_for()
    {
        $this->__load();
        return parent::getLooking_for();
    }

    public function setLooking_for($looking_for)
    {
        $this->__load();
        return parent::setLooking_for($looking_for);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getInterests()
    {
        $this->__load();
        return parent::getInterests();
    }

    public function setInterests($interests)
    {
        $this->__load();
        return parent::setInterests($interests);
    }

    public function getEducation()
    {
        $this->__load();
        return parent::getEducation();
    }

    public function setEducation($education)
    {
        $this->__load();
        return parent::setEducation($education);
    }

    public function getHobbies()
    {
        $this->__load();
        return parent::getHobbies();
    }

    public function setHobbies($hobbies)
    {
        $this->__load();
        return parent::setHobbies($hobbies);
    }

    public function getFav_movies()
    {
        $this->__load();
        return parent::getFav_movies();
    }

    public function setFav_movies($fav_movies)
    {
        $this->__load();
        return parent::setFav_movies($fav_movies);
    }

    public function getFav_artists()
    {
        $this->__load();
        return parent::getFav_artists();
    }

    public function setFav_artists($fav_artists)
    {
        $this->__load();
        return parent::setFav_artists($fav_artists);
    }

    public function getFav_books()
    {
        $this->__load();
        return parent::getFav_books();
    }

    public function setFav_books($fav_books)
    {
        $this->__load();
        return parent::setFav_books($fav_books);
    }

    public function getFav_animals()
    {
        $this->__load();
        return parent::getFav_animals();
    }

    public function setFav_animals($fav_animals)
    {
        $this->__load();
        return parent::setFav_animals($fav_animals);
    }

    public function getReligion()
    {
        $this->__load();
        return parent::getReligion();
    }

    public function setReligion($religion)
    {
        $this->__load();
        return parent::setReligion($religion);
    }

    public function getEverything_else()
    {
        $this->__load();
        return parent::getEverything_else();
    }

    public function setEverything_else($everything_else)
    {
        $this->__load();
        return parent::setEverything_else($everything_else);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function setLanguage($language)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getNickname()
    {
        $this->__load();
        return parent::getNickname();
    }

    public function setNickname($nickname)
    {
        $this->__load();
        return parent::setNickname($nickname);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'profile_id', 'relationship', 'looking_for', 'about_me', 'language', 'gender', 'nickname', 'phone', 'interests', 'education', 'hobbies', 'fav_movies', 'fav_artists', 'fav_books', 'fav_animals', 'religion', 'everything_else', 'address', 'email', 'privacy_type_id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}